### PR TITLE
Expand types to allow for more selectors

### LINKED ISSUE #25: Expanding SelectorCreator Types
Hi @josepot! Thanks for creating this library.

We're currently using reselect heavily in one of our projects and are looking for an easier/higher-performance way to organize our selectors. Your library seems to really fit the bill, but I'm encountering a problem when using it. Some of our selectors have up to 16 input selectors, which is currently not supported by the types in this project. I haven't found a way to extend the types in our project internally, because of the way `createSelector`'s type is defined. Would you be open to me creating a PR to define types for more input selectors? Or is there a way to extend the types within our project that I haven't found?

### PR DESCRIPTION
**Pull request by helgenlechner**
Fixes #25 by adding types to allow up to 16 different input selectors.

### CODE REVIEW

**Comment by voliva** [comment]
Hey, thanks for the work, but I'm pretty convinced that it would be possible to have a solution that would allow for any number of sub selectors - As typescript has greatly improved in rest `(...arguments: Array<...>)` and mapped tuple types.

This evening I can give it a try to see if I can come up with a general solution for this.

**Comment by helgenlechner** [comment]
@voliva Sure, that would be great. Thank you! But will this also work if the library users still have an older version of TypeScript? We're still on 3.8.3, for example, and I think those improvements you're talking about are very recent.

**Comment by josepot** [comment]
> @voliva Sure, that would be great. Thank you! But will this also work if the library users still have an older version of TypeScript? We're still on 3.8.3, for example, and I think those improvements you're talking about are very recent.

What if we wait for @voliva to finish #27 and then we [use the `typesVersions` field](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions) to support both definitions?

**Comment by josepot** [comment]
On a second thought: I'm going to merge this PR, then I will publish a patch with these changes (1.0.2), and when #27 is ready then we will publish another patch that will support both TS >4.1 and legacy.

**Pull request merged**
